## Build and test as standard C++ package
xenial-cpp-build:
  stage: build
  image: rduweston/ubuntu-ci:16.04
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . && cpack

xenial-cpp-test:
  stage: test
  image: rduweston/ubuntu-ci:16.04
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build && cd build
    - cmake -DBUILD_TESTS=ON ..
    - cmake --build .
    - ./bin/gtest_all

bionic-cpp-build:
  stage: build
  image: rduweston/ubuntu-ci:18.04
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . && cpack

bionic-cpp-test:
  stage: test
  image: rduweston/ubuntu-ci:18.04
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build && cd build
    - cmake -DBUILD_TESTS=ON ..
    - cmake --build .
    - ./bin/gtest_all

focal-cpp-build:
  stage: build
  image: rduweston/ubuntu-ci:20.04
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . && cpack

focal-cpp-test:
  stage: test
  image: rduweston/ubuntu-ci:20.04
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build && cd build
    - cmake -DBUILD_TESTS=ON ..
    - cmake --build .
    - ./bin/gtest_all

## Build and test as catkin package
kinetic-catkin-build:
  stage: build
  image: rduweston/ubuntu-ci:kinetic
  script:
    - mkdir -p /catkin_ws/src && cd /catkin_ws/src && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_init_workspace"
    - cp -r /builds/$CI_PROJECT_PATH /catkin_ws/src/wrp_sdk
    - cd /catkin_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_make"

kinetic-catkin-isolated-build:
  stage: build
  image: rduweston/ubuntu-ci:kinetic
  script:
    - mkdir -p /catkin_ws/src && cd /catkin_ws/src && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_init_workspace"
    - cp -r /builds/$CI_PROJECT_PATH /catkin_ws/src/wrp_sdk
    - cd /catkin_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_make_isolated --install"

melodic-catkin-build:
  stage: build
  image: rduweston/ubuntu-ci:melodic
  script:
    - mkdir -p /catkin_ws/src && cd /catkin_ws/src && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_init_workspace"
    - cp -r /builds/$CI_PROJECT_PATH /catkin_ws/src/wrp_sdk
    - cd /catkin_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_make"

melodic-catkin-isolated-build:
  stage: build
  image: rduweston/ubuntu-ci:melodic
  script:
    - mkdir -p /catkin_ws/src && cd /catkin_ws/src && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_init_workspace"
    - cp -r /builds/$CI_PROJECT_PATH /catkin_ws/src/wrp_sdk
    - cd /catkin_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_make_isolated --install"

noetic-catkin-build:
  stage: build
  image: rduweston/ubuntu-ci:noetic
  script:
    - mkdir -p /catkin_ws/src && cd /catkin_ws/src && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_init_workspace"
    - cp -r /builds/$CI_PROJECT_PATH /catkin_ws/src/wrp_sdk
    - cd /catkin_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_make"

noetic-catkin-isolated-build:
  stage: build
  image: rduweston/ubuntu-ci:noetic
  script:
    - mkdir -p /catkin_ws/src && cd /catkin_ws/src && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_init_workspace"
    - cp -r /builds/$CI_PROJECT_PATH /catkin_ws/src/wrp_sdk
    - cd /catkin_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_make_isolated --install"